title: Blockchain Deadlines
description: Deadline countdowns for high-quality academic venues relevant to blockchain
author: Blockchain Deadlines

domain: "blockchain-deadlines.github.io"
baseurl: ""

twitter_hashtag: blockchain
github_username: blockchain-deadlines
github_repo: blockchain-deadlines.github.io

markdown: kramdown
ga_id:

include: ['_pages']
